spring:
  application:
    name: spring-boot-kotlin-ktorm
  datasource:
    url: jdbc:postgresql://localhost:5432/pikumar?currentSchema=public
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create # toggle to none once db schema is created.
    show-sql: true